### ISSUE TITLE
Problem when on native Browser

### ISSUE THREAD

**Issue by hanashiro** [Joncom/impact-font2#5]
It works fine on Chrome, but when I'm using on native browser ( the same when build with Phonegap/Cordova ), it happens:

![nnc6g6fnqkysmjl4k5riyetbv9qso5nd7arv9fgoflw](https://cloud.githubusercontent.com/assets/4622398/11517131/ea5d9f2a-986e-11e5-93f6-ae8da3237344.png)

**Comment by Joncom** [comment]
Seems to work on my Android browsers...

![Screenshot 1](http://i.imgur.com/4XYApE3.png)
![Screenshot 2](http://i.imgur.com/C2BRYsb.png)

Are you able to provide a simple test case containing the issue that I could try on my end?

What Android device are you running on, and with what version of Android?

**Comment by hanashiro** [comment]
I tested on my tablet (samsung galaxy note 8.0, android 4.4) and on my smartphone (samsung galaxy core 2 duos, android 4.3)

on my code:
>font: new ig.Font( 'media/arialblack14.font.png', { borderColor: '#000' } )

the font file: (the font is white, but is here below :smile: )
> ![arialblack14 font](https://cloud.githubusercontent.com/assets/4622398/11519924/9873fd00-9885-11e5-8ef6-0d67116382f2.png)

**Comment by Joncom** [comment]
Hmm. Even with your font, everything seems to work fine on my Android. Would you mind running this test on your device and see if it it still has rendering issues? 

https://github.com/Joncom/impact-font-border-test

**Comment by hanashiro** [comment]
Weird, here the test is ok. :disappointed:
I will continue investigating what might be causing this.

**Comment by Joncom** [comment]
A technique I like for solving issues like this: copy your repository (or better yet, create a new branch), and start ripping out irrelevant code, committing as you go. As you rip stuff out, keep checking if the program is still broken. Eventually you will rip out the thing that's causing the issue, and that's a win. Or, you'd tear out so much stuff that all you have left is a very simple test case that contains the issue. And with that, finding the source of the problem is only a few steps away.

**Comment by hanashiro** [comment]
I was working on another project, and when I came back surprisingly this bug gone away.
Maybe it was a bug from the browser.
Thanks for the help.

**Comment by Joncom** [comment]
Haha, interesting...
